backend:
  name: github
  repo: akhil-naidu/gatsby-theme-nehalem

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: demo/content/posts/{{slug}}
    create: true
    slug: "{{slug}}"
    
    fields:
      - { name: title, label: Title, widget: string }
      - { name: path, label: Path }
      - { name: tags, label: Tags }
      - { name: featuredImage, label: featuredImage, widget: image }
      - { name: exert, label: Exert, widget: string }
      - { name: created, label: Created, widget: date }
      - { name: updated, label: Updated, widget: date }
      - { name: body, label: Body, widget: markdown }
