backend:
  name: git-gateway
  repo: master
  identity_url: "https://blog.leewardslope.com/.netlify/identity"
  squash_merges: true
   
publish_mode: editorial_workflow
media_folder: "demo/content/posts/blog/assets"
      
  - name: blog
    label: Blog
    folder: "demo/content/posts/blog"
    create: true
    slug: "{{slug}}"
    preview_path: "{{permalink}}"
    editor:
      preview: false
    
    fields:
      - { name: title, label: Title, widget: string }
      - { name: path, label: Path }
      - { name: tags, label: Tags, widget: list }
      - { name: Image, label: Featured Image, widget: image }
      - { name: featuredImage, label: Image Location, widget: string }
      - { name: excerpt, label: Excerpt, widget: string }
      - { name: created, label: Created, widget: date }
      - { name: updated, label: Updated, widget: date }
      - { name: body, label: Body, widget: markdown }
