backend:
  name: git-gateway
  repo: akhil-naidu/gatsby-theme-nehalem

media_folder: demo/content/posts/blog/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: "demo/content/posts/blog"
    create: true
    slug: "{{slug}}"
    
    fields:
      - { name: title, label: Title, widget: string }
      - { name: path, label: Path }
      - { name: tags, label: Tags }
      - { name: image, label: Featured Image, widget: image }
      - { name: featuredImage, label: Image Location, widget: string }
      - { name: exert, label: Exert, widget: string }
      - { name: created, label: Created, widget: date }
      - { name: updated, label: Updated, widget: date }
      - { name: body, label: Body, widget: markdown }
